name: CI
on:
  push:
    branches:
      - main

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu/squid:5.2-22.04_beta
      env:
        TZ: UTC
      ports:
        - 3128:3128
    steps:
      - name: Get Public IP
        run: echo "This is a new line.\nAnd this is a tab: \t."

