# name: CI
# on:
#   push:
#     branches:
#       - main

# jobs:
#   container-test-job:
#     runs-on: ubuntu-latest
#     container:
#       image: ubuntu/squid:5.2-22.04_beta
#       env:
#         TZ: UTC
#       ports:
#         - 3128:3128 
#     steps:
#       - name: Use curl
#         uses: sozo-design/curl@v1.0.2
#         with:
#           args: https://httpbin.org/get 
          
# name: CI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   container-test-job:
#     runs-on: ubuntu-latest
#     container:
#       image: ubuntu/squid:5.2-22.04_beta
#       env:
#         TZ: UTC
#       ports:
#         - 3128:3128
#     steps:
#       - name: Use curl
#         uses: sozo-design/curl@v1.0.2
#         with:
#           args: https://httpbin.org/get         
#       - name: Start Squid proxy
#         run: squid -N -d 1




name: CI
on:
  push:
    branches:
      - main

jobs:
  squid-container-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use curl
        uses: sozo-design/curl@v1.0.2
        with:
          args: https://httpbin.org/get     
      - name: Set up Docker
        uses: docker/setup-qemu-action@v1
      - name: Run squid container
        run: |
        if: always()
          docker run -d --name squid-container -e TZ=UTC -p 3128:3128 ubuntu/squid:5.2-22.04_beta
      - name: Get container IP
        run: |
          CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' squid-container)
          echo "Container IP: $CONTAINER_IP"
      - name: Keep container running
        run: tail -f /dev/null

