# name: CI
# on:
#   push:
#     branches:
#       - main

# jobs:
#   container-test-job:
#     runs-on: ubuntu-latest
#     container:
#       image: ubuntu/squid:5.2-22.04_beta
#       env:
#         TZ: UTC
#       ports:
#         - 3128:3128 
#     steps:
#       - name: Use curl
#         uses: sozo-design/curl@v1.0.2
#         with:
#           args: https://httpbin.org/get 
          
name: CI

on:
  push:
    branches:
      - main

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu/squid:5.2-22.04_beta
      env:
        TZ: UTC
      ports:
        - 3128:3128
    steps:
      - name: Use curl with proxy
        run: curl --proxy http://localhost:3128 https://httpbin.org/get        
      - name: Start Squid proxy
        run: squid -N -d 1

