name: CI
on:
  push:
    branches:
      - main

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu/squid:5.2-22.04_beta
      env:
        TZ: UTC
      ports:
        - 3128:3128
    steps:
      - name: Get Public IP
        uses: champ-oss/action-get-public-ip@v1
        id: ip

      - name: Check Public IP
        run: |
          echo "IPv4: ${{ steps.ip.outputs.ipv4 }}"
          echo "IPv6: ${{ steps.ip.outputs.ipv6 }}"
